name: pygbag_build
on: [push]

permissions:
  contents: write

jobs:  
  build-pygbag:
    name: Build for Emscripten
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'true'
    - name: Checkout
      run: |
            python3 -m pip install pygbag
            python3 -m pygbag --build $GITHUB_WORKSPACE

    - name : "Upload to GitHub pages"
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build/web